FROM --platform=$BUILDPLATFORM debian:12.10@sha256:18023f131f52fc3ea21973cabffe0b216c60b417fd2478e94d9d59981ebba6af AS node_builder
WORKDIR /

# ARG NODE_VERSION
ARG NODE_VERSION=v20.18.0

RUN apt update && apt install -y git make python3 file binutils todo


RUN git clone --branch $NODE_VERSION --depth=1 --recursive --shallow-submodules https://github.com/nodejs/node
WORKDIR /node

ENV CC=s390x-linux-gnu-gcc
ENV CXX=s390x-linux-gnu-g++

RUN ./configure --verbose \
    --fully-static --enable-static \
    --dest-os=linux --dest-cpu=s390x \
    --without-corepack --without-npm --without-inspector \
    --disable-single-executable-application --with-intl=small-icu \
    --enable-lto --v8-options="--max-old-space-size=1024 --max-semi-space-size=128"

RUN make -j$(($(nproc) - 1))

RUN out/Release/node -v || true

RUN cd out/Release && file node && ls -lah node && \
    s390x-linux-gnu-strip node && \
    file node && ls -lah node

FROM ghcr.io/arca-consult/scratch:v0.0.1@sha256:b9b0d504760dfbecfb519b74b97200f3e9dc484393d7fc14e24db41f760634bb AS runner

COPY --from=node_builder /node/out/Release/node /node
ENTRYPOINT ["/node"]
