FROM --platform=$BUILDPLATFORM debian:bookworm@sha256:321341744acb788e251ebd374aecc1a42d60ce65da7bd4ee9207ff6be6686a62 AS node_builder
WORKDIR /

# ARG NODE_VERSION
ARG NODE_VERSION=v20.18.0

RUN apt update && apt install -y git make python3 gcc g++ gcc-multilib g++-multilib

RUN git clone --depth=1 https://github.com/rvagg/rpi-newer-crosstools.git

ENV CC=/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-gcc
ENV CXX=/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-g++
ENV LD=/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-ld
ENV AR=/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-ar

ENV CC_host="gcc -m32"
ENV CXX_host="g++ -m32"

RUN git clone --branch $NODE_VERSION --depth=1 --recursive --shallow-submodules https://github.com/nodejs/node

RUN cd node && ./configure --verbose \
    --fully-static --enable-static \
    --dest-os=linux --dest-cpu=arm \
    --without-corepack --without-npm --without-inspector \
    --disable-single-executable-application --with-intl=small-icu \
    --v8-options="--max-old-space-size=1024 --max-semi-space-size=128"

RUN cd node && make -j$(nproc)

FROM ghcr.io/arca-consult/scratch:v0.0.1@sha256:b9b0d504760dfbecfb519b74b97200f3e9dc484393d7fc14e24db41f760634bb AS runner

COPY --from=node_builder /node/node /node
ENTRYPOINT ["/node"]