FROM --platform=$BUILDPLATFORM docker.io/debian:12.9@sha256:10901ccd8d249047f9761845b4594f121edef079cfd8224edebd9ea726f0a7f6 AS node_builder
WORKDIR /

ARG NODE_VERSION
# ARG NODE_VERSION=v20.18.0

RUN apt update && apt install -y git make python3 file gcc g++ gcc-multilib g++-multilib

RUN git clone --depth=1 https://github.com/rvagg/rpi-newer-crosstools.git
RUN git clone --branch $NODE_VERSION --depth=1 --recursive --shallow-submodules https://github.com/nodejs/node
WORKDIR /node

ENV CC="/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-gcc -gdwarf-4"
ENV CXX="/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-g++ -gdwarf-4"
ENV LD="/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-ld"
ENV AR="/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-ar"

ENV CC_host="gcc -m32 -gdwarf-4"
ENV CXX_host="g++ -m32 -gdwarf-4"

# without lto
RUN ./configure --verbose \
    --fully-static --enable-static \
    --dest-os=linux --dest-cpu=arm \
    --without-corepack --without-npm --without-inspector \
    --disable-single-executable-application --with-intl=small-icu \
    --v8-options="--max-old-space-size=1024 --max-semi-space-size=128"

RUN make -j$(($(nproc) - 1))

RUN out/Release/node -v || true

RUN cd out/Release && file node && ls -lah node && \
    /rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-strip node && \
    file node && ls -lah node

FROM ghcr.io/arca-consult/scratch:0.0.2@sha256:ea3be3c3643833df48d7883c3f0caa9b891087d3b88ff553e2f3a928d7c267bd AS runner

COPY --from=node_builder /node/out/Release/node /node
ENTRYPOINT ["/node"]
