FROM --platform=$BUILDPLATFORM debian:bookworm AS node_builder
WORKDIR /node

ARG NODE_VERSION
# ARG NODE_VERSION=v20.18.0

RUN apt update && apt install -y git make python3 binutils gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu

RUN git clone --branch $NODE_VERSION --depth=1 --recursive --shallow-submodules https://github.com/nodejs/node

ENV CC=aarch64-linux-gnu-gcc
ENV CXX=aarch64-linux-gnu-g++

RUN cd node && ./configure --verbose \
    --fully-static --enable-static \
    --dest-os=linux --dest-cpu=arm64 \
    --without-corepack --without-npm --without-inspector \
    --disable-single-executable-application --with-intl=small-icu \
    --enable-lto --v8-options="--max-old-space-size=1024 --max-semi-space-size=128"

RUN cd node && make -j$(nproc)

RUN echo 'nobody:x:65534:65534:Nobody:/:' > /tmp/passwd

FROM scratch AS runner

COPY --from=node_builder /node/node/node /node
COPY --from=node_builder /tmp/passwd /etc/passwd
COPY --from=node_builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=node_builder /usr/share/zoneinfo /usr/share/zoneinfo

ENTRYPOINT ["/node"]