FROM --platform=$BUILDPLATFORM debian:12.9@sha256:4abf773f2a570e6873259c4e3ba16de6c6268fb571fd46ec80be7c67822823b3 AS builder
RUN apt update && apt install ca-certificates -y
RUN echo 'nobody:x:65534:65534:Nobody:/:' > /tmp/passwd

FROM scratch AS runner
COPY --from=builder /tmp/passwd /etc/passwd
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
USER 65534:65534