FROM --platform=$BUILDPLATFORM debian:bookworm@sha256:10901ccd8d249047f9761845b4594f121edef079cfd8224edebd9ea726f0a7f6 AS node_builder
WORKDIR /

ARG NODE_VERSION
# ARG NODE_VERSION=v20.18.0

RUN apt update && apt install -y git make python3 files

RUN git clone --depth=1 https://github.com/rvagg/rpi-newer-crosstools.git

ENV PATH="$PATH:/rpi-newer-crosstools/x64-gcc-12.3.0-glibc-2.28/arm-rpi-linux-gnueabihf/bin"
ENV CXX=arm-rpi-linux-gnueabihf-g++
ENV CC=arm-rpi-linux-gnueabihf-gcc
ENV LD=arm-rpi-linux-gnueabihf-ld
ENV AR=arm-rpi-linux-gnueabihf-ar
ENV RANLIB=arm-rpi-linux-gnueabihf-ranlib

RUN git clone --branch $NODE_VERSION --depth=1 --recursive --shallow-submodules https://github.com/nodejs/node
WORKDIR /node

RUN ./configure --verbose \
    --fully-static --enable-static \
    --dest-os=linux --dest-cpu=arm \
    --without-corepack --without-npm --without-inspector \
    --disable-single-executable-application --without-intl \
    --v8-options="--max-old-space-size=1024 --max-semi-space-size=128"

RUN  make -j$(nproc)

RUN cd out/Release && file node && ls -lah node && \
    arm-rpi-linux-gnueabihf-strip node && \
    file node && ls -lah node

FROM ghcr.io/arca-consult/scratch:v0.0.1@sha256:b9b0d504760dfbecfb519b74b97200f3e9dc484393d7fc14e24db41f760634bb AS runner

COPY --from=node_builder /node/out/Release/node /node
ENTRYPOINT ["/node"]