FROM --platform=$BUILDPLATFORM docker.io/debian:12.9@sha256:10901ccd8d249047f9761845b4594f121edef079cfd8224edebd9ea726f0a7f6 AS node_builder
WORKDIR /

ARG NODE_VERSION
# ARG NODE_VERSION=v20.18.0

RUN apt update && apt install -y git make python3 file gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu


RUN git clone --branch $NODE_VERSION --depth=1 --recursive --shallow-submodules https://github.com/nodejs/node
WORKDIR /node

ENV CC=aarch64-linux-gnu-gcc
ENV CXX=aarch64-linux-gnu-g++

RUN ./configure --verbose \
    --fully-static --enable-static \
    --dest-os=linux --dest-cpu=arm64 \
    --without-corepack --without-npm --without-inspector \
    --disable-single-executable-application --with-intl=small-icu \
    --enable-lto --v8-options="--max-old-space-size=1024 --max-semi-space-size=128"

RUN make -j$(($(nproc) - 1))

RUN out/Release/node -v || true

RUN cd out/Release && file node && ls -lah node && \
    aarch64-linux-gnu-strip node && \
    file node && ls -lah node

FROM ghcr.io/arca-consult/scratch:0.0.2 AS runner

COPY --from=node_builder /node/out/Release/node /node
ENTRYPOINT ["/node"]
