FROM --platform=$BUILDPLATFORM debian:bookworm AS builder
RUN apt update && apt install ca-certificates -y
RUN echo 'nobody:x:65534:65534:Nobody:/:' > /tmp/passwd

FROM scratch AS runner
COPY --from=builder /tmp/passwd /etc/passwd
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
USER 65534:65534