FROM --platform=$BUILDPLATFORM docker.io/debian:trixie@sha256:ad1a494fd8dac6ff85bbc76e03edf98b3064a096bf79f641f91316e28d478f2d AS node_builder
WORKDIR /

ARG NODE_VERSION
# ARG NODE_VERSION=v20.18.0
                                    
RUN apt update && apt install -y git make python3 file gcc g++ gcc-s390x-linux-gnu g++-s390x-linux-gnu

RUN git clone --branch $NODE_VERSION --depth=1 --recursive --shallow-submodules https://github.com/nodejs/node
WORKDIR /node

ENV CC="s390x-linux-gnu-gcc"
ENV CXX="s390x-linux-gnu-g++"
ENV LD="s390x-linux-gnu-ld"
ENV AR="s390x-linux-gnu-ar"

ENV CC_host="gcc"
ENV CXX_host="g++"
ENV LD_host="ld"
ENV AR_host='ar'

# without lto
RUN ./configure --verbose --cross-compiling \
    --fully-static --enable-static \
    --dest-os=linux --dest-cpu=s390x \
    --without-corepack --without-npm --without-inspector \
    --disable-single-executable-application --with-intl=small-icu \
    --v8-options="--max-old-space-size=1024 --max-semi-space-size=128"
    
RUN make -j$(($(nproc) - 1))

RUN out/Release/node -v || true

RUN cd out/Release && file node && ls -lah node && \
    s390x-linux-gnu-strip node && \
    file node && ls -lah node

FROM ghcr.io/arca-consult/scratch:0.0.2@sha256:ea3be3c3643833df48d7883c3f0caa9b891087d3b88ff553e2f3a928d7c267bd AS runner

COPY --from=node_builder /node/out/Release/node /node
ENTRYPOINT ["/node"]
